### ISSUE TITLE
Broken recipe

### ISSUE THREAD

**Issue by RealMrMango** [GregTechCEu/gregicality-science#25]
Vacuum tube components appear to be using the old assembler recipe for making Vacuum tubes

**Comment by TechLord22** [comment]
If you have the harder vacuum tubes config enabled, the assembler recipe will also make the components. There should also be a crafting recipe with the config enabled. If there is not, that is a bug.

**Comment by RealMrMango** [comment]
the recipe is  1 steel bolt ,  copper wires and a glass tube (for the vacuum tube components) so I am guessing that it's a bug?

**Comment by TechLord22** [comment]
Ah that is indeed a bug. It should not need two vacuum tubes total to produce.

**Comment by TechLord22** [comment]
Fixed as of ef4c843.
