### ISSUE TITLE
Dryer tooltip broken

### ISSUE THREAD

**Issue by Leclowndu93150** [GregTechCEu/gregicality-science#26]
### GregTech CEu Version

e

### Gregicality Multiblocks Version

e

### Gregicality Science Version

lmao

### Modpack Used

e

### Environment

e

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

e

### Actual Behavior

![2022-08-12_20 00 11](https://user-images.githubusercontent.com/73310949/184417060-a13cfc79-a8b6-44d7-992d-60589f5d43e2.png)

### Steps to Reproduce

e

### Additional Information

e

**Comment by TechLord22** [comment]
Fixed in cc72d30.
