### ISSUE TITLE
Ammonia config is not working

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#30]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

        Disables production of Ammonia from Oxygen and Hydrogen, requiring Gregicality's process.
        B:disableAmmoniaProcessing=true -> you can make ammonia from Nitrogen and Hydrogen in neither CR nor LCR

### Actual Behavior

        Disables production of Ammonia from Oxygen and Hydrogen, requiring Gregicality's process.
        B:disableAmmoniaProcessing=true -> you can make ammonia from Nitrogen and Hydrogen in LCR

someone probably forgot banning LCR

### Steps to Reproduce

install GCYS

### Additional Information

also see #27

**Comment by TechLord22** [comment]
Fixed in [ab1afcb](https://github.com/GregTechCEu/gregicality-science/commit/ab1afcb75f6643941a3432c379c41c4d33d829c2).
