### ISSUE TITLE
Nanoscale Fabricator JEI preview cannot display available crucibles

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#33]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

When you right click Quartz Crucible in Nanoscale Fabricator JEI preview, you can see all available crucibles for Nanoscale Fabricator

### Actual Behavior

![キャプチャ1475](https://user-images.githubusercontent.com/39122497/184426767-7a94a548-cb1c-46f6-926d-bcd669105af0.PNG)

### Steps to Reproduce

install GCYS

**Comment by TechLord22** [comment]
Fixed in [fd76233](https://github.com/GregTechCEu/gregicality-science/commit/fd762338d633c469de4cfc1a607a1511454e0fb7).
