### ISSUE TITLE
can't progress after LuV

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#34]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

you can obtain Cubic Zirconia to craft Crystal SoC to make a new circuit in LuV

### Actual Behavior

Cubic Zirconia has no recipe

### Steps to Reproduce

install GCYS

**Comment by TechLord22** [comment]
This will be fixed once base CEu nuclear is added, and Zirconium becomes obtainable.
