### ISSUE TITLE
"Steps to Reproduce" in Bug Report template should not be marked as necessary

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#35]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Your Solution

There are many bugs in GCYS but most of bugs are recipe bugs
these bugs have no step to reproduce so "Steps to Reproduce" is redundant

**Comment by TechLord22** [comment]
It is important to require the steps for reproduction, as making it optional will lead to it simply being ignored for non-recipe bugs, which can only cause further headache. Simply saying "this is a recipe bug" or similar is plenty for reproduction steps of recipe issues. Additionally, a recipe bug may only appear with cross-mod interaction, which should be stated in reproduction steps as well.

**Comment by Quarri6343** [comment]
alright
thanks
