### ISSUE TITLE
Butanediol decomp recipe is unbalanced

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#42]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Butanediol C4H8(OH)2 => Diacetyl C4H6O2 + Hydrogen H *4

### Actual Behavior

![キャプチャ1484](https://user-images.githubusercontent.com/39122497/184519540-f44c31d9-9400-4f0e-84e5-968baa85c34a.PNG)

### Steps to Reproduce

install GCYS

**Comment by TechLord22** [comment]
Fixed in c9aa03a.
