### ISSUE TITLE
Sodium Chlorate Recipe is duplicated

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#43]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Sodium Chlorate can be made from salt and water and int circuit

### Actual Behavior

there are 2 same recipe to make Sodium Chlorate dust
one requires int circuit while other doesn't

### Steps to Reproduce

install GCYS

**Comment by bruberu** [comment]
The latter recipe is not a GCYS recipe, it is a GTFO recipe. This is also now fixed on GTFO's master by not adding the recipe when GCYS is loaded.
