### ISSUE TITLE
Cannot obtain Sodium Perchlorate

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#44]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

no conflicting recipe

### Actual Behavior

![キャプチャ1485](https://user-images.githubusercontent.com/39122497/184519771-e4e256a1-ffe2-4778-984d-3b7e1b58b144.PNG)
![キャプチャ1486](https://user-images.githubusercontent.com/39122497/184519773-15adfb82-d87a-4f81-aa40-dcdb5f425db4.PNG)

### Steps to Reproduce

install GCYS

**Comment by bruberu** [comment]
The latter recipe is not a GCYS recipe, it is a GTFO recipe. This is also now fixed on GTFO's master by adding a configuration circuit to the first recipe.
