### ISSUE TITLE
Citric Acid and Stearic Acid and Sodium Stearates subscript format is incorrect

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#45]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

they have subscript as a small character

### Actual Behavior

![キャプチャ1487](https://user-images.githubusercontent.com/39122497/184519906-b5cc26f9-e85f-4567-9519-4cdd742d6c93.PNG)

### Steps to Reproduce

install GCYS

**Comment by bruberu** [comment]
These are not GCYS materials, these are GTFO materials. This is also now fixed on GTFO's master.
