### ISSUE TITLE
Cannot obtain first Carbon Nanotube

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#47]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

you can obtain carbon nanotube

### Actual Behavior

Carbon Nanotube dust -> Carbon Allotrope Mixture -> Graphene-Aligned  Carbon Nanotube -> Cycloparaphenylene -> Carbon Nanotube Ingot (single line chain)

### Steps to Reproduce

install GCYS

**Comment by TechLord22** [comment]
Carbon Nanotubes are first produced as a Long Rod.
