### ISSUE TITLE
TurboMolecular Pump tooltip Typo

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#51]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

consumes 100L/s Lubricant when decreasing pressure

### Actual Behavior

consumes 100L/se Lubricant when decreasing pressure

happens in both low power and high power

### Steps to Reproduce

this is UI bug

**Comment by TechLord22** [comment]
Fixed in 49c2889.
