### ISSUE TITLE
Cannot obtain Rubidium

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#52]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

rubidium dust has a recipe

### Actual Behavior

rubidium dust and small dust and tiny dust have no recipe

### Steps to Reproduce

this is a recipe bug

**Comment by TechLord22** [comment]
Fixed in b9bc8a8.

**Comment by TechLord22** [comment]
Closed the wrong issue...
