### ISSUE TITLE
Super and Ultimate Circuit Board recipe does not require Cleanroom

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#53]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

every high tier circuit board requires cleanroom

### Actual Behavior

title

### Steps to Reproduce

this is a recipe bug

**Comment by TechLord22** [comment]
Fixed in b9bc8a8.
