### ISSUE TITLE
Ruthenium Trinium Americium Neutronate Wire is marked as UHV superconductor

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#54]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Ruthenium Trinium Americium Neutronate Wire is high tier superconductor

### Actual Behavior

it is UHV superconductor although it requires neutronium

### Steps to Reproduce

this is item feature bug

**Comment by TechLord22** [comment]
Fixed in 2d21f3c,
