### ISSUE TITLE
Cannot make Rotary Hearth Furnace and Bulk Blast Chiller in UHV

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#55]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

Rotary Hearth Furnace and Bulk Blast Chiller does not require neutronium to make

### Actual Behavior

they do

### Steps to Reproduce

this is a recipe bug

**Comment by TechLord22** [comment]
Fixed in 0ec4f3a.
