### ISSUE TITLE
Incorrect amount of Sodium Peroxide

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#56]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

2 Na + 2 O = Na2O2

### Actual Behavior

![キャプチャ1493](https://user-images.githubusercontent.com/39122497/184640209-e8ee6172-7c00-42e8-aaee-ae0ebb5c121d.PNG)

### Steps to Reproduce

this is a recipe bug

**Comment by TechLord22** [comment]
This recipe is using that same reaction, divided by two. `2 Na + 2 O -> Na2O2`, would mean 2 Sodium Dust + 2000 Oxygen -> 4 Sodium Peroxide Dust. As the quantities are all divisible by two here, we can have the recipe be 1 Sodium Dust + 1000 Oxygen -> 2 Sodium Peroxide Dust.
