### ISSUE TITLE
Hydrogen and Oxygen loss on EDOT recipe

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#60]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

no loss

### Actual Behavior

SCl2 + C2H4(OH)2 + C4H6O2 -> C6H6O2 + 2HCl
Hx12 -> Hx8
Ox4 -> Ox2

### Steps to Reproduce

this is a recipe bug

**Comment by pablocnvs** [comment]
H2O is lost as intended
