### ISSUE TITLE
Duplicated Rotary Hearth Furnace (and Bulk Blast Chiller) recipes

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/gregicality-science#64]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Rotary Hearth Furnace has one recipe

### Actual Behavior

![image](https://user-images.githubusercontent.com/39122497/185023129-bea04839-1e7a-4d0b-aa2e-bd70cf8cce42.png)

### Steps to Reproduce

this is a recipe bug

**Comment by TechLord22** [comment]
This is fixed with an upcoming release of GCYM meant to be used in coordination with the next alpha of GCYS.
