### ISSUE TITLE
Many zirconium-related things are missing

### ISSUE THREAD

**Issue by Quaerere-Git** [GregTechCEu/gregicality-science#79]
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1-alpha

### Environment

Forge Server

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Zirconium can be produced from a certain recipe for late-game ZBLAN glass in optical circuit chain.

### Actual Behavior

Neither zirconium nor cubic zirconia can be produced from other recipes, meaning it unobtainable in survival without cheating.

### Steps to Reproduce

1)Look up the recipe related to zirconium in JEI;
2)Look up the recipe related to cubic zirconia in JEI;
3)Only recipes among zirconium or cubic zirconia stuff are found.

**Comment by Quarri6343** [comment]
Duplication of #34
